defaults:
  - _self_
  - env: finger
  - alg: ppo

general:
  logdir: logs
  param_dir: params
  seed: 42
  debug: false

wandb:
  project: fd_brax
  entity: mistry-lab
  group: ${alg.name}
  resume: False
